mysite/blog/urls.py
"""
A URL pattern is composed of a string pattern, view and optionally
a name to name the URL project wide.

When a URL match is found - Django imports the view of the matching
URL pattern and executes it, passing an instance of HTTPRequest
and the kwarg or args.

Creating a URLs per application is the best way to make your applications reusable by other projects
"""
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = "blog"  # application namespace (organize URLs by application)

urlpatterns = [
    # post views
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    # path(
    # "", views.PostListView.as_view(), name="post_list"
    # ),  # Use the class based view instead
    # Use angle brackets to capture values from URL
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls", namespace="blog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    )
    # You can refer to URLS using blog:post_list and blog:post_detail for example
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here - each model will create a table


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status="published")


class Post(models.Model):
    """
    The name of the table 'blog_post' is derived from model metadata - but can be overriden
    'id' - field is automatically created this behaviour can be overriden.
    The 'settings' file will drive out the SQL syntax to use based on the DB that is there.
    """

    objects = (
        models.Manager()
    )  # The default manager - if you want to add your own managers and keep default you must add it
    published = PublishedManager()  # Custom manager

    # Don't use field names that conflict with the Models api - clean, save, delete (for example)
    # For choices, first value in tuple is what is in db, second is displayed by field's form widget
    STATUS_CHOICES = (
        ("draft", "Draft"),
        ("published", "Published"),
    )

    title = models.CharField(max_length=250)  # Translates to VARCHAR
    slug = models.SlugField(
        max_length=250, unique_for_date="publish"
    )  # Used for URL, unique_for_date prevents duplicate slugs for posts with same publish date and slug
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )  # Many to One (one user can create many blog posts).
    # on_delete - CASCADE will ensure all blog posts by a deleted user are deleted
    body = models.TextField()  # Translates to TEXT
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(
        auto_now_add=True
    )  # auto_now_add - date is saved automatically when object is created
    updated = models.DateTimeField(auto_now=True)
    # auto_now - date is updated when saving an object
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default="draft"
    )  # Can only be from the STATUS_CHOICES given

    tags = (
        TaggableManager()
    )  # Allows you to add tags to the post, ordering of fields drives ordering in admin UI

    class Meta:
        # Contains the metadata - sort results by the 'publish' field in descending order
        ordering = ("-publish",)
        # default_manager_name can specify a different default manager

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """
        Use in templates to link to specific posts
        :return: Canonical URL for the Post model that can be used as a specific URL for the model resource
        """
        # self.publish.year/month/day - The year reference does not exist until it is dynamically built at runtime
        # noinspection PyUnresolvedReferences
        return reverse(
            "blog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    # FK to associate a single comment with a single post. Many to 1 - each post can have many comments
    # related_name attribute - names the attribute you use for the relationship from one object to the other,
    # this allows you to do comment.post and post.comments.all()
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    """
    auto_now_add - set field to now when object is first created. If you set a value for this field
    on creation - it will be ignored unless auto_now_add=True. Useful for 'created' fields
    auto_now_add, auto_now and default are mutually exclusive - any combination will cause an error.
    auto_now_add and auto_now (as of writing) - when set to True will set editable=False and blank=True
    """
    created = models.DateTimeField(auto_now_add=True)
    """
    auto_now - automatically sets the field to now every time the object is saved. Useful for last-modified fields.
    This value cannot be overridden. This is only updated on Model.save()
    """
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ("created",)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

mysite/blog/forms.py
from django import forms
from .models import Comment

# Standard convention is to add forms inside a forms.py for each application


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)  # max_length is a validation field
    email = forms.EmailField()  # manages email validation for you
    to = forms.EmailField()
    # The widget attribute overrides the default widget - here Textarea is used instead of <input> element
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # indicates which model to use to build the form - Django builds the form dynamically
        fields = ("name", "email", "body")


class SearchForm(forms.Form):
    query = forms.CharField()

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Post, Comment
from django.views.generic import ListView
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.contrib.postgres.search import TrigramSimilarity

# Create your views here - a view is just Python function that receives a web req and returns a response
# All logic to return desired response goes inside the view
# Views can be defined as class methods - the advantages are that organizing code related to HTTP methods is cleaner
# Class based views allow for multiple inheritance (to encourage re use)


class PostListView(ListView):
    queryset = Post.published.all()  # Use a specific QuerySet for retrieving objects
    context_object_name = "posts"  # Use context variable posts for query results
    paginate_by = 3  # Paginate the result - display 3 objects per page
    template_name = "blog/post/list.html"  # Use custom templat to render page


def post_list(request, tag_slug=None):  # request param required by all views
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(
            tags__in=[tag]
        )  # filter list by ones containing tag

    paginator = Paginator(
        object_list, 3
    )  # 3 posts per page - Instantiate Paginator class with number of objects to display per page
    page = request.GET.get(
        "page"
    )  # Get the page GET param indicating current page number
    try:
        posts = paginator.page(
            page
        )  # obtain the objects for the desired page by calling page() of Paginator
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    # Use render() to render the list of posts with the template
    # Takes request context into account (template context processors are callables that set variables into the context)
    return render(
        request, "blog/post/list.html", {"page": page, "posts": posts, "tag": tag}
    )


def post_detail(request, year, month, day, post):
    post = get_object_or_404(
        Post,
        slug=post,
        status="published",
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    # List of active comments for this post
    comments = post.comments.filter(
        active=True
    )  # QuerySet used - use post object to get the Comment objects

    new_comment = None

    if request.method == "POST":
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        # Create comment form - if GET
        comment_form = CommentForm()

    # List of similar posts
    """
    Retrieve a Python list of IDs for the tags of the current post, flat=True
    ensures you get a list of single values rather than tuples
    """
    post_tag_ids = post.tags.values_list("id", flat=True)
    """
    You then get all published posts with these tags excluding the post itself
    """
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    """
    Your order the result by the number of shared tags and by publish to display the most recent posts 
    first with the same number of tags. You then slice the result to get the first four posts
    """
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "blog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "new_comment": new_comment,
            "comment_form": comment_form,
            "similar_posts": similar_posts,
        },
    )


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status="published")  # Retrieve post
    sent = False
    if request.method == "POST":
        # Form was submitted
        form = EmailPostForm(
            request.POST  # contains the submitted data
        )  # Use same view for displaying and processing
        if form.is_valid():  # validates data in form
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message, "admin@myblog.com", [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()  # displays an empty form
    return render(
        request, "blog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if "query" in request.GET:  # is form submitted
        form = SearchForm(
            request.GET
        )  # GET is used so its easy to share the URL (rather than POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            results = (
                Post.published.annotate(similarity=TrigramSimilarity("title", query))
                .filter(similarity__gt=0.1)
                .order_by("-similarity")
            )  # Order by SearchRank to order by relevancy
    return render(
        request,
        "blog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

mysite/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% endfor %}
    {%  with comments.count as total_comments %} <!-- With allows you to assign a value to new variable-->
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }} <!-- Use pluralize to display a plural suffix depending on total_comments value - adds "s" if value is different to 1-->
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are not comments yet.</p>
    {% endfor %}
    {%  if new_comment %}
        <h2>Your comment has been added</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

mysite/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
            {% endfor %}
        </p>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30}}
        <!--truncatewords and linebreaks are template filters - applied to output -->
    {% endfor %}
    {% include "pagination.html" with page=posts %} <!-- Changed pagination - ListView generic view passes
     selected page in variable called page_obj, so edit post/list.html -->
{% endblock %}

mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{  post.title }}</a> </h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
        {% else %}
            <h1>Search for posts</h1>
            <form method = "get">
                {{ form.as_p }}
                <input type="submit" value="Search">
            </form>
    {% endif %}
{% endblock %}

mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}

<!-- This will display the form or success message when an email is sent. -->
{% block content %}
    {%  if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <!-- Create a form - to be submitted by POST method-->
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            <!-- The following tells Django to render its fields in the <p> elements.-->
            {{ form.as_p }}
            <!-- Introduces hidden fields with auto generated token to avoid CSRF-->
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}